name: Bug report
description: When a bug exists only in TLG and not DDA
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. Repeatedly submitting duplicate issues may lead to consequences.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A description of what you're experiencing. You can also put "See title." if sufficiently simple. You can also upload screenshots.
    placeholder: The game throws an error when I try to…
  validations:
    required: true
- type: textarea
  attributes:
    label: Upload your save (optional)
    description: |
      If the issue can only be reproduced with a specific save.
      1. Press `ESC` and then `d` to enter the debug menu.
      2. Press `i` to enter "Info…"
      3. Press `!` to generate a minimized save archive.
    placeholder: Drag and drop your file here!
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Load save.
      2. Do this specific thing.
      3. The game crashes.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: What it is supposed to do. Leave empty on crashes and the like.
    placeholder: |
      Instead of taking 5 potatoes, it should only require 4 since the calories of the result are too low for 5 potatoes.
  validations:
    required: false
- type: textarea
  attributes:
    label: Game version
    description: |
      The version you are using. If you use many mods, please narrow down what mod it is causing first.
      1. Press `ESC` and then `d` to enter the debug menu.
      2. Press `i` to enter "Info…"
      3. Press `r` generate information about your game.
    placeholder: The report is automatically copied. Paste it here!
  validations:
    required: true
